vich_uploader:
    db_driver: orm
    metadata:
        type: attribute
    mappings:
        monuments_images:
            uri_prefix: /images/monuments
            upload_destination: '%kernel.project_dir%/public/images/monuments'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
