vich_uploader:
    db_driver: orm
    metadata:
        type: attribute

    mappings:
        accomodation_images:
            uri_prefix: /images/hebergement
            upload_destination: '%kernel.project_dir%/public/images/hebergement'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
