vich_uploader:
    db_driver: orm
    metadata:
        type: attribute 

    mappings:
        guide_images:
           uri_prefix: /images/imageguide
           upload_destination: '%kernel.project_dir%/public/images/imageguide'
           namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
