vich_uploader:
    db_driver: orm
    metadata:
        type: attribute 

    mappings:
        guide_images:
            uri_prefix: /images/imageguide
            upload_destination: '%kernel.project_dir%/public/images/imageguide'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
        accomodation_images:
            uri_prefix: /images/hebergement
            upload_destination: '%kernel.project_dir%/public/images/hebergement'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
        monuments_images:
            uri_prefix: /images/monuments
            upload_destination: '%kernel.project_dir%/public/images/monuments'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
