#index:
#    path: /
#    controller: App\Controller\DefaultController::index
captcha_routing:
      resource: "@CaptchaBundle/Resources/config/routing.yml"
monument_details:
    path: /details/{id}
    controller: App\Controller\TestController::details
